TeachingManagement/AssignmentYearApp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.shortcuts import redirect
from .import views

urlpatterns = [
    #For the COURSES
    path('section-courses/', views.section_courses_list, name='section_courses_list'),
    path('section-courses/show/<int:idCourseYear>/', views.courseyear_show, name='courseyear_show'),

        #For updating only the comment in a CourseYear
    path('update-course-year-comment/<int:idCourseYear>/', views.update_course_year_comment, name='update_course_year_comment'),
        #modifyning the points of a professor Assigned in a Course Year
    path('update-assignment/<int:idAssignment>/', views.update_assignment, name='update_assignment'),
        #assigning a new professor in the CoureYear
    path('assign_professor/<int:professor_id>/<int:course_year_id>/', views.assign_professor, name='assign_professor'),
        #deleting the assign points of one professor in one Course
    path('delete_professor/<int:idProfessor>/<int:idCourseYear>/', views.delete_courseyear_professor, name='delete_courseyear_professor'),

    #For DUPLICATING   
        #for selecting original year - selected year
    path('select-years/', views.select_years_for_duplication, name='select_years'),
        #for making the duplication
    path('course/duplicate/<int:idCourseYear>/', views.duplicate_course_assignment, name='duplicate_course_assignment'),

    #For the PROFESSORS
    path('section-professors/', views.section_professors_list, name='section_professors_list'),

]

TeachingManagement/ProfessorApp/urls.py
from django.urls import path
from .import views

app_name='professorapp'

urlpatterns = [
    path('', views.professor_dashboard, name='professor_dashboard'),

    path('info/', views.info_assignments, name='info_assignments'),
    path('download_info_assigments/', views.generate_assignments_pdf, name='generate_info_pdf'),

    path('details-professor/<int:professor_id>/year/<int:year_id>/',views.professor_year_assignments_summary, name='professor_details'),
    path('download_info_assigments/<int:professor_id>/year/<int:year_id>/', views.generate_professor_year_assignments_pdf, name='generate_info_pdf_given_professor'),

]

TeachingManagement/TeachingManagement/urls.py
from django.contrib import admin
from django.urls import path,include
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda request: redirect('baseapp/', permanent=True)),  # Redirect root URL to /baseapp/

    path('baseapp/',include('TeachingManagementApp.urls')),  # URL for every APP - TeachingManagementApp
   
    #functionalities for users in app + their functionalities
    path('users/',include('UsersApp.urls')),  # URL for every APP - UsersApp
   
    #for Directors + their functions
    path('director/',include('DirectorApp.urls')),  # URL for every APP - DirectorApp
    path('academicinfo/',include('AcademicInfoApp.urls')),  # URL for every APP - AcademicInfoApp
    path('professorsection/',include('ProfSectionCapacityApp.urls')),  # URL for every APP - ProfSectionCapacity

    #For section chiefs + their functions
    path('sectionchief/',include('SectionChiefApp.urls')),  # URL for every APP - SectionChiefApp
    path('infosection/',include('AssignmentYearApp.urls')),  # URL for every APP - AssignmentYearApp

    #For professor + their functions
    path('professor/',include('ProfessorApp.urls')), # URL for every APP - ProfessorApp

    path('admin/', admin.site.urls),
]

TeachingManagement/UsersApp/urls.py
from django.urls import path
from . import views,services

app_name = 'usersapp'

urlpatterns = [
    # use names for easy calls + functions reverse() and {% url %}  
    path('login/', views.login_session, name='login'),
    path('logout/', views.logout_session, name='logout'),
    
    #Professors 
    path('professor/', views.professor_list, name='professor_list'),
    path('professor/create/', views.professor_create_edit, name='professor_create'),
    path('professor/edit/<int:idProfessor>', views.professor_create_edit, name='professor_edit'),

    path('professor/export/',  services.generate_professor_excel, name='professor_export'), 
    path('professor/upload/',  services.upload_professor_excel, name='professor_upload'), 

    #Section chiefs
    path('sectionchief/', views.sectionchief_list, name='sectionchief_list'),
    path('sectionchief/create/', views.sectionchief_create_edit, name='sectionchief_create'),
    path('sectionchief/edit/<int:idChief>', views.sectionchief_create_edit, name='sectionchief_edit'),

    ]

TeachingManagement/AssignmentYearApp/models.py
from django.db import models
from UsersApp.models import Professor
from ProfSectionCapacityApp.models import CourseYear

# Create your models here.

class Assignment(models.Model):
    idAssignment = models.AutoField(primary_key=True)
    CourseYear = models.ForeignKey(CourseYear, on_delete=models.CASCADE)
    Professor = models.ForeignKey(Professor, on_delete=models.CASCADE)
    PointsA = models.DecimalField(max_digits=5, decimal_places=2,null=True, blank=True)
    PointsB = models.DecimalField(max_digits=5, decimal_places=2,null=True, blank=True)
    PointsC = models.DecimalField(max_digits=5, decimal_places=2,null=True, blank=True)
    PointsD = models.DecimalField(max_digits=5, decimal_places=2,null=True, blank=True)
    PointsE = models.DecimalField(max_digits=5, decimal_places=2,null=True, blank=True)
    PointsF = models.DecimalField(max_digits=5, decimal_places=2,null=True, blank=True)
    isCoordinator = models.BooleanField(default=False)

    class Meta:
        verbose_name='assignment'
        verbose_name_plural='assignments'
        unique_together = ('Professor', 'CourseYear')  # Ensure unique combinations


    def __str__(self):
        return f"{self.Professor.name} {self.Professor.family_name} {self.CourseYear.Course.NameCourse}  {self.CourseYear.Year.Year}"

TeachingManagement/AssignmentYearApp/forms.py
from django import forms
from ProfSectionCapacityApp.models import CourseYear

class CourseYearCommentForm(forms.ModelForm):
    class Meta:
        model = CourseYear
        fields = ['Comment']
        widgets = {
            'comment': forms.Textarea(attrs={'class': 'form-control auto-save', 'rows': 2, 'data-id': '{{ course_year.idCourseYear }}'}),
        }

TeachingManagement/AssignmentYearApp/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .utils import get_sectionchief_section
from AcademicInfoApp.models import Course,Degree,Year,School
from ProfSectionCapacityApp.models import CourseYear,TypePoints
from UsersApp.models import Professor,ProfessorField,ProfessorLanguage
from ProfSectionCapacityApp.models import Capacity,Free,CapacitySection
from .models import Assignment
from django.urls import reverse
from django.http import JsonResponse
import json
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Sum
from decimal import Decimal

# Create your views here.

""" View to update the selected year in the session."""
def select_year(request):
    if 'year' in request.GET:
        request.session['selected_year'] = request.GET['year']
    
    # Redirect to the page that submitted the form or reload the current page
    referer_url = request.META.get('HTTP_REFERER')
    
    if referer_url:
        return redirect(referer_url)
    else:
        return redirect(reverse('sectionchiefapp:sectionchief_dashboard'))

# COURSES found in that SECTION - IN ALL SCHOOLS - IN ALL DEGREES
def section_courses_list(request):
    user=request.user

    section= get_sectionchief_section(user) # return the section of the chief

    # get SELECTED YEAR - if not selected have the most recent one
    years = Year.objects.all().order_by('-Year').distinct()
    year = request.GET.get('year', None)
    
    if year:
        request.session['selected_year'] = year  #global variable selected year saved in the session
    else:
        year = request.session.get('selected_year', None)
        if not year and years:
            year = years.first().Year  #most recent one


    year_obj = Year.objects.get(Year=year)

    #return COURSES associated with the section, year, and schools/degrees
    course_years  = CourseYear.objects.filter(
        Course__Degree__School__Section=section, 
        Year=year_obj.idYear
    ).select_related('Course', 'Year', 'Course__Degree')

    #return NAMES of the TYPE of POINTS
    typepoints_section=TypePoints.objects.filter(
        Section=section, 
        Year=year_obj.idYear 
    ).first()

    #extract the NAMES OF TYPE POINTS of that section - only save the not empty names 
    typepoint_names = []
    if typepoints_section:
        typepoint_fields = ['NamePointsA', 'NamePointsB', 'NamePointsC', 'NamePointsD', 'NamePointsE', 'NamePointsF']
        for field in typepoint_fields:
            point_name = getattr(typepoints_section, field)
            if point_name:  
                typepoint_names.append(point_name)
    
    typepoint_names_assigned={}
    #Dicc to have the names linked for the possible points
    typepoints_fields = {
        'PointsA': typepoints_section.NamePointsA if typepoints_section else None,
        'PointsB': typepoints_section.NamePointsB if typepoints_section else None,
        'PointsC': typepoints_section.NamePointsC if typepoints_section else None,
        'PointsD': typepoints_section.NamePointsD if typepoints_section else None,
        'PointsE': typepoints_section.NamePointsE if typepoints_section else None,
        'PointsF': typepoints_section.NamePointsF if typepoints_section else None,
    }
    #Only save the names of the groups that are not None
    for field, point_name in typepoints_fields.items():
        if point_name is not None:
            typepoint_names_assigned[field] = point_name
    
    course_data = [] #all info of ONE COURSE
   
    for course_year in course_years:
        total_points = {}
        total_course_points = 0         #total points TO assign in the course - initial points
        total_assigned_points = 0       #total ALREADY assigned points - where professors wil be assigned
        
        # Return info of TOTAL POINTS - that will need to be assigned that Course year
        total_points = {}
        for field, point_name in typepoint_names_assigned.items():
            point_value = getattr(course_year,field, 0) or 0
            total_points[point_name] = point_value
        
            total_course_points = sum(value if value is not None else 0 for value in total_points.values())
        
        #Return info of INFO POINTS ALREADY ASSIGNED x professor that Course year
        #return ASSIGNEDPOINTSS from assignment
        assigned_points = {name: 0 for name in typepoint_names}
        assignments = Assignment.objects.filter(CourseYear=course_year)

        for assignment in assignments:
            for field, point_name in typepoint_names_assigned.items():
                assigned_value = getattr(assignment, field, 0) or 0
                if assigned_value is not None:
                    assigned_points[point_name] += assigned_value

        total_assigned_points = sum(value if value is not None else 0 for value in assigned_points.values())
        
        # Create formatted string for each point type in "Group: assigned/total" format
        points_summary = ""
        # for point_name in typepoint_names:
        for field, point_name in typepoint_names_assigned.items():
            assigned_value = assigned_points.get(point_name, 0)
            total_value = total_points.get(point_name, 0)
            points_summary += f"{point_name}: {assigned_value}/{total_value}, "

        # Remove the trailing comma and space
        points_summary = points_summary.strip(', ')

        #INFO X COURSE
        course_data.append({
            'id':course_year.idCourseYear,
            'degree': course_year.Course.Degree.NameDegree,
            'course': course_year.Course.NameCourse,
            'semester': course_year.Semester,
            'year':course_year.Year,

            'total_course_points': total_course_points,
            'total_assigned_points': total_assigned_points,
                        
            'points_summary':points_summary,
        })

    course_data = sorted(course_data, key=lambda x: (x['degree'], x['semester'] == "Q2"))
    
    context = {
        'course_data': course_data, 
        'section': section,
    }   
    return render(request, 'section_courses_assign/courses_assign_list_actions.html', context)

def courseyear_show(request,idCourseYear=None):
    course_year = get_object_or_404(CourseYear, pk=idCourseYear)

    section = course_year.Course.Degree.School.Section
    # Return NAMES of the TYPE of POINTS for the course's section and year
    typepoints_section = TypePoints.objects.filter(
        Section=section,
        Year=course_year.Year
    ).first()

    #extract the NAMES OF TYPE POINTS of that section - only save the not empty names 
    typepoint_names = []
    if typepoints_section:
        typepoint_fields = ['NamePointsA', 'NamePointsB', 'NamePointsC', 'NamePointsD', 'NamePointsE', 'NamePointsF']
        for field in typepoint_fields:
            point_name = getattr(typepoints_section, field)
            if point_name:  
                typepoint_names.append(point_name)

    typepoint_names_assigned={}
    #Dicc to have the names linked for the possible points
    typepoints_fields = {
        'PointsA': typepoints_section.NamePointsA if typepoints_section else None,
        'PointsB': typepoints_section.NamePointsB if typepoints_section else None,
        'PointsC': typepoints_section.NamePointsC if typepoints_section else None,
        'PointsD': typepoints_section.NamePointsD if typepoints_section else None,
        'PointsE': typepoints_section.NamePointsE if typepoints_section else None,
        'PointsF': typepoints_section.NamePointsF if typepoints_section else None,
    }
    #Only save the names of the groups that are not None
    for field, point_name in typepoints_fields.items():
        if point_name is not None:
            typepoint_names_assigned[field] = point_name
    
    #return TOTALPOINTS from CourseYear
    total_points_sum=0
    total_points = {}
    for field, point_name in typepoint_names_assigned.items():
        point_value = getattr(course_year,field, 0) or 0
        total_points[point_name] = point_value
    
        total_points_sum = sum(value if value is not None else 0 for value in total_points.values())

    #return ASSIGNEDPOINTSS from assignment
    assigned_points_sum=0
    assigned_points = {name: 0 for name in typepoint_names}
    assignments = Assignment.objects.filter(CourseYear=course_year)

    for assignment in assignments:
        for field, point_name in typepoint_names_assigned.items():
            assigned_value = getattr(assignment, field, 0) or 0
            if assigned_value is not None:
                assigned_points[point_name] += assigned_value

    assigned_points_sum = sum(value if value is not None else 0 for value in assigned_points.values())


    #return ONLY the ASSIGNED PROFESSORS - it will be in the Assignment table in that CourseYear
    assignments = Assignment.objects.filter(CourseYear=course_year)

    #Save the info of the PROFESSORS already assgned
    assignment_data = []
    for assignment in assignments:
        data = {}
        data['id']=assignment.idAssignment
        data['is_coordinator']=assignment.isCoordinator

        data['professor_name'] = assignment.Professor.name +" "+assignment.Professor.family_name
        data['professor_id'] = assignment.Professor.idProfessor
        
        for field, point_name in typepoint_names_assigned.items():
            value = getattr(assignment, field, None) or 0
            data[point_name] = f"{value:.2f}".replace(',', '.')

        assignment_data.append(data)    
    # Query for all professors that are either assigned or not assigned to the courseYear
    assigned_professors = Professor.objects.filter(
        idProfessor__in=Assignment.objects.filter(CourseYear=course_year).values('Professor_id')
    )

    unassigned_professors = Professor.objects.filter(isActive=True).exclude(

TeachingManagement/AssignmentYearApp/templates/professor_info_assign/professor_assign_info_list_actions.html
{% extends 'base-template/base.html' %}

{% load custom_filters %}

{% block title %} Professorat - {{ section.NameSection }}{% endblock %}

{% block content %}
<div class="container-fluid d-flex" style="min-height: 100vh;">
    <div class="col-lg-10 mx-auto">
        <h2 style="text-align:center"> Professorat de: {{ section.NameSection }} - Curs: {{global_selected_year}} </h2>

        <!-- Display success, warning, or error messages -->
        {% if messages %}
            <div class="messages">
                {% for message in messages %}
                    <div class="{% if message.tags %}alert alert-{{ message.tags }}{% endif %}">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}

        <hr>

        <div class="row">
            <div class="col-lg-12 mx-auto" >
              
                <!-- Filter Fields -->
                <h3>Filtres pel pofessorat</h3>
                <div class="d-flex justify-content-between row mb-2">
                    <!-- Filters section -->
                    <div class="filters d-flex flex-wrap">
                        <div class="col-md-12 p-0">
                            <label for="filter-all">Filtrar per contingut</label>
                            <input type="text" id="filter-all" class="form-control" placeholder="Cerca per nom, cognom i % total">
                        </div>
                    </div>

                </div>
                
                <hr>

                <h3>Llistat del professorat</h3>

                <table class="table" id="professorssection-table"  style="table-layout: fixed;">
                    <thead>
                        <tr>   
                            <th class="name-c" style="text-align: left; width: 15%;" >Nom i cognom</th>
                            <th style="text-align: left; width:95px;">% Total</th>
                            <th style="text-align: left; width:8%;">Punts Q1</th>
                            <th style="text-align: left; width:8%;">Punts Q2</th>
                            <th style="text-align: center; width:10%;">Capacitat docent al departament</th>
                            <th style="text-align: center; width:9%;">Capacitat docent a la secció</th>
                            <th style="text-align: left; width: 8%;">Punts no assignats a la secció</th> 
                            {% for schools in schools_section %}
                                <th style="text-align: left; font-style: italic">{{ schools.NameSchool }}</th>
                            {% endfor %}
                            <th class="actions-c" style="width:100px">Acció</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if professor_section_data %}
                            {% for professor in professor_section_data %}
                                <tr data-name="{{ professor.name }} {{professor.family_name}}"
                                    data-percentatge="{{professor.point_percentage}}"
                                    {% if professor.point_percentage < 10 %}
                                        style="background-color: rgba(95, 95, 107, 0.2);" 
                                    {% elif professor.point_percentage < 70 %}
                                        style="background-color: rgba(255, 99, 71, 0.2);"
                                    {% elif professor.point_percentage >= 70 and professor.point_percentage < 90 %}
                                        style="background-color: rgba(255, 215, 0, 0.2);"
                                    {% endif %}
                                    >
                                    <td>{{ professor.name }} {{professor.family_name}}</td>
                                    <td  {% if professor.point_percentage < 10 %}
                                            style="color: grey;"
                                        {% elif professor.point_percentage < 70 %}
                                            style="color:red;"
                                        {% elif professor.point_percentage >= 70 and professor.point_percentage < 90 %}
                                            style="color: #fba92b;"
                                        {% elif professor.point_percentage >= 90 %}
                                            style="color:green;"
                                        {% endif %}
                                        > 
                                        <strong>{{ professor.point_percentage|floatformat:"-2"  }} % </strong> 
                                    </td>
                                    <td>{{ professor.pointsQ1|floatformat:"-2" }}</td>
                                    <td>{{ professor.pointsQ2|floatformat:"-2" }}</td>
                                    <td style="text-align: center;">  
                                        {% if professor.total_capacity == 0 %}
                                            --
                                        {% else %}
                                            {{ professor.total_capacity|floatformat:"-2" }}
                                        {% endif %}
                                    </td>
                                    <td>
                                        {% if professor.capacity_section == 0 %}
                                            --
                                        {% else %}
                                            {{ professor.capacity_section|floatformat:"-2" }}
                                        {% endif %}
                                    </td>

                                    <td>
                                        {{ professor.points_not_assigned|floatformat:"-2" }}
                                    </td>
                                    {% for school in schools_section %}
                                        <td style="text-align: left; font-style: italic; color:blue">
                                            {% for point_data in professor.points_for_schools %}
                                                {% if point_data.school_name == school.NameSchool %}
                                                    {% if point_data.points == 0 %}
                                                        -
                                                    {% else %}
                                                        <strong>{{ point_data.points|floatformat:"-2" }}</strong>
                                                    {% endif %}
                                                {% endif %}
                                            {%endfor %}
                                        </td>
                                    {% endfor %}                    
                                    <td class="actions-c" style="width:100px">
                                        <!-- Edit button -->
                                        <a href="{% url 'professorapp:professor_details' professor.professor_id year.idYear %}" class="button-create btn-sm">Detalls</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        {% else %}
                            <tr>
                                <td colspan="12" class="text-center">Cap assignació docent en cap professorat en aquesta secció.</td>
                            </tr>        
                        {% endif %} 
                    </tbody>
                </table>
                
                <!-- No results message -->
                <div id="no-results-message" class="text-center text-danger" style="display:none;">
                    <span id="no-results-text"></span>
                </div>
            </div>
            
        </div>
    </div>
</div>

<!-- JavaScript function for confirmation -->
<script>

    function toggleDetails(row) {
        // Find the next row, which is the details row
        let detailsRow = row.nextElementSibling;
        if (detailsRow && detailsRow.classList.contains('professor-details-row')) {
            detailsRow.style.display = detailsRow.style.display === 'none' ? 'table-row' : 'none';
        }
    }
        
    //Not using  accents in the filter and in the data
    function normalizeString(str) {
        return str.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
    }

    // JavaScript for dynamic filtering
    document.getElementById('filter-all').addEventListener('input', filterTable);

    function filterTable() {
        const searchValue = normalizeString(document.getElementById('filter-all').value);
        const tableRows = document.querySelectorAll('#professorssection-table tbody tr');

        let rowsVisible = 0;

        tableRows.forEach(row => {
            const fieldName = row.getAttribute('data-name') ? normalizeString(row.getAttribute('data-name')) : '';
            const fieldP = row.getAttribute('data-percentatge')|| '';
            
            const matchesSearch = fieldName.includes(searchValue) || fieldP.includes(searchValue) ||
            (searchValue === "0" && (fieldP === "0.00" || fieldP === "0.0" || fieldP === "0"));
            
            if (matchesSearch) {
                row.style.display = '';
                rowsVisible++;
            } else {
                row.style.display = 'none';
            }
          
        });

        const noResultsMessage = document.getElementById('no-results-message');
        const noResultsText = document.getElementById('no-results-text');

        // No results message logic
        if (rowsVisible === 0) {
            let message = "Cap Professor amb els criteris de cerca";
            if (searchValue) {
                message += ` amb el terme "${searchValue}"`;
            }
            noResultsText.textContent = message + ".";
            noResultsMessage.style.display = 'block';
        } else {
            noResultsMessage.style.display = 'none';
        }
    }
</script>



{% endblock %}