TeachingManagement/DirectorApp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.shortcuts import redirect
from .import views

app_name='directorapp'

urlpatterns = [
    path('dashboard/', views.director_dashboard, name='director_dashboard'),

]

TeachingManagement/TeachingManagement/urls.py
from django.contrib import admin
from django.urls import path,include
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda request: redirect('baseapp/', permanent=True)),  # Redirect root URL to /baseapp/

    path('baseapp/',include('TeachingManagementApp.urls')),  # URL for every APP - TeachingManagementApp
   
    #functionalities for users in app + their functionalities
    path('users/',include('UsersApp.urls')),  # URL for every APP - UsersApp
   
    #for Directors + their functions
    path('director/',include('DirectorApp.urls')),  # URL for every APP - DirectorApp
    path('academicinfo/',include('AcademicInfoApp.urls')),  # URL for every APP - AcademicInfoApp
    path('professorsection/',include('ProfSectionCapacityApp.urls')),  # URL for every APP - ProfSectionCapacity

    #For section chiefs + their functions
    path('sectionchief/',include('SectionChiefApp.urls')),  # URL for every APP - SectionChiefApp
    path('infosection/',include('AssignmentYearApp.urls')),  # URL for every APP - AssignmentYearApp

    #For professor + their functions
    path('professor/',include('ProfessorApp.urls')), # URL for every APP - ProfessorApp

    path('admin/', admin.site.urls),
]

TeachingManagement/UsersApp/urls.py
from django.urls import path
from . import views,services

app_name = 'usersapp'

urlpatterns = [
    # use names for easy calls + functions reverse() and {% url %}  
    path('login/', views.login_session, name='login'),
    path('logout/', views.logout_session, name='logout'),
    
    #Professors 
    path('professor/', views.professor_list, name='professor_list'),
    path('professor/create/', views.professor_create_edit, name='professor_create'),
    path('professor/edit/<int:idProfessor>', views.professor_create_edit, name='professor_edit'),

    path('professor/export/',  services.generate_professor_excel, name='professor_export'), 
    path('professor/upload/',  services.upload_professor_excel, name='professor_upload'), 

    #Section chiefs
    path('sectionchief/', views.sectionchief_list, name='sectionchief_list'),
    path('sectionchief/create/', views.sectionchief_create_edit, name='sectionchief_create'),
    path('sectionchief/edit/<int:idChief>', views.sectionchief_create_edit, name='sectionchief_edit'),

    ]

TeachingManagement/DirectorApp/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required,user_passes_test

# Create your views here.
def is_director(user):
    return user.role == 'director'

@login_required
@user_passes_test(is_director)
def director_dashboard(request):
    return render(request, 'director_dashboard.html')

TeachingManagement/DirectorApp/templates/director_dashboard.html
{% extends 'base-template/base.html' %}
{% load tz %}

{% block title %}Director - SASDOC 2.0{% endblock %}

{% block content %}
<div class="dashboard container mt-4">

    <h1 class="text-center">TAULER DIRECTOR@</h1>

    <h3 class="text-center">Benvingut, Director {{ user.username }}</h3>
    {% now "l, F j, Y" as current_date %} 

    <p class="text-center">Data: {{ current_date }}</p>

    <div class="list-group mt-4">

        <div class="list-group-item">
            <h4>Gestió de Professorat</h4>
            <p>Aquí podràs gestionar els professors, incloent-hi crear, editar i eliminar professors.</p>
            <a href="{% url 'usersapp:professor_list' %}" class="btn btn-primary">Accedir</a>
        </div>

        <div class="list-group-item">
            <h4>Gestió de Caps de Secció</h4>
            <p>Aquí podràs gestionar els caps de secció, incloent-hi la seva creació, edició i eliminació.</p>
            <a href="{% url 'usersapp:sectionchief_list' %}" class="btn btn-primary">Accedir</a>
        </div>

        <div class="list-group-item">
            <h4>Gestió Acadèmica</h4>
            <p>Aquesta secció et permet gestionar els camps, seccions, escoles, graus, cursos i tipus de professors per mantenir un registre actualitzat de la informació acadèmica.</p>
            <a href="{% url 'field_list' %}" class="btn btn-primary">Accedir</a>
        </div>

        <div class="list-group-item">
            <h4>Gestió d'Anys i Idiomes</h4>
            <p>Controla els anys acadèmics i els idiomes d'ensenyament disponibles per cada curs i professor.</p>
            <a href="{% url 'language_list' %}" class="btn btn-primary">Accedir</a>
        </div>

    </div>
</div>
{% endblock %}